spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:static,file:./images,file:./static,file:./temp
  web:
    resources:
      static-locations: classpath:static,file:./images,file:./static,file:./temp
#  redis:
#    #Redis数据库索引（默认为0）
#    database: 0
#    # Redis服务器地址
#    host: localhost
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password:
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-wait: 1
#        # 连接池中的最大空闲连接 默认 8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认 0
#        min-idle: 0

server:
  port: 20049
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000
    max-http-header-size: 8096

auth:
  super:
    pwd: 000000
  pwd: 123456

