spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb0?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  main:
    web-application-type: none
  resources:
    static-locations: classpath:static,file:./images,file:./static,file:./temp
  web:
    resources:
      static-locations: classpath:static,file:./images,file:./static,file:./temp

mybatis-plus:
  configuration:
    #缓存开启
    cache-enabled: true