spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:static,file:./images,file:./static,file:./temp
  web:
    resources:
      static-locations: classpath:static,file:./images,file:./static,file:./temp

server:
  port: 20049
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000
    max-http-header-size: 8096

auth:
  pwd: 123456

mc:
  ip: localhost
  port: 20043
  gid: 794238572