bot-291984860:
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/gdb1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
bot-930204019:
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/gdb1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/gdb2?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:static,file:./images,file:./static,file:./temp
  web:
    resources:
      static-locations: classpath:static,file:./images,file:./static,file:./temp

mybatis-plus:
  configuration:
    #缓存开启
    cache-enabled: true

server:
  port: 20049
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000
    max-http-header-size: 8096

web:
  url: http://localhost
  pwd: 123456

auth:
  super:
    pwd: 123456
  pwd: 123456

