spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: file:./images,file:./static,file:./temp
  web:
    resources:
      static-locations: file:./images,file:./static,file:./temp

server:
  port: 20049


